version: '3.8'

services:

  hub:
    image: selenium/hub
    environment:
      - GRID_MAX_SESSION=5
      - GRID_NEW_SESSION_WAIT_TIMEOUT=300000
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=10

  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=10

  #app:
    #build:
      #context: .
      #shm_size: '1gb'